apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gg4ffjvhj-python-gitops
  description: This is GitOps manifest for gg4ffjvhj-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gg4ffjvhj-python
    backstage.io/kubernetes-id: gg4ffjvhj-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gg4ffjvhj-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gg4ffjvhj-python
