apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gg4ffjvhj-python
  janus-idp.io/tekton: gg4ffjvhj-python
  backstage.io/kubernetes-id: gg4ffjvhj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gg4ffjvhj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
